### ISSUE TITLE
Add results on public benchmarks

### ISSUE THREAD

**Issue by wouterkool** [PyVRP/PyVRP#30] opened 2023-01-10 09:48 UTC
There are many repositories solving VRP. To be convincing as SOTA solver, we should add a (summary) results table in README including running time and gap to BKS.

Some options for VRPTW:
- Solomon cases (DIMACS objective)
- Gehring & homberger cases (DIMACS objective)
- EURO Meets NeurIPS qualificaton cases (DIMACS objective)

If we support minimizing vehicles (or perform runs with known minimal number of vehicles):
- Solomon & GH according to [SINTEF objective](https://www.sintef.no/projectweb/top/vrptw/1000-customers/). Bonus: we could also perform long runs and see if we can register new BKS at SINTEF

If we also support CVRP
- Uchoa et al. dataset from [CVRPlib](http://vrp.galgos.inf.puc-rio.br/index.php/en/)

More benchmarks can be found at [VRP-REP](http://www.vrp-rep.org/variants/item/vrptw.html)

**Comment by N-Wouda** [comment] 2023-05-18 21:30
I'm revisiting this issue with some (long overdue) updates. 

As benchmark instances, we have used the X instances of Uchoa et al. for CVRP, and the GH1000 instances for VRPTW. This is documented in [our benchmarking section of the docs](https://pyvrp.readthedocs.io/en/latest/dev/benchmarking.html). For prize-collecting VRPTW, I generated a few new instances deriving from GH1000 (details [here](https://github.com/PyVRP/Instances/blob/main/PC-VRPTW/README.md) in `PyVRP/Instances`). These new instances need to make their way to VRP-REP at some point. Probably after DIMACS next week. 

We currently compare everything using the DIMACS objective. We have worked a bit on supporting double precision as well, rather than just integers. Between PRs #169 and #210, I think we will have a really clean solution using simple templated wrapper structs around a double or integer value. An implementation is in the works in those PRs, but will not land in `main` until after DIMACS.

**Comment by N-Wouda** [comment] 2023-09-11 13:40
I'm closing this issue since we have figured the benchmarking part out pretty well:
- Benchmarks are available [here](https://pyvrp.org/setup/benchmarks.html), all using DIMACS conventions. We support double precision, but don't (currently) use that in our benchmarking.
- How PyVRP is benchmarked is explained [here](https://pyvrp.org/dev/benchmarking.html). I think this is sufficient in terms of clarity/reproducibility.

Both of these are updated as PyVRP supports new features, with every new substantial release.

**Closed by N-Wouda** 2023-09-11 13:40 UTC
