### ISSUE TITLE
Heterogeneous fleet example hangs

### ISSUE THREAD

**Issue by leonlan** [PyVRP/PyVRP#380] opened 2023-09-04 11:05 UTC
#### Is your feature request related to a problem? Please describe
I have found a heterogeneous fleet instance that hangs. This example hangs when ran locally and also on Google colaboratory.
Note that it doesn't hang when the runtime is set to say 1 second.

```python
from pyvrp import Model

COORDS = [
    (456, 320),  # location 0 - the depot
    (228, 0),    # location 1
    (912, 0),    # location 2
    (0, 80),     # location 3
    (114, 80),   # location 4
    (570, 160),  # location 5
    (798, 160),  # location 6
    (342, 240),  # location 7
    (684, 240),  # location 8
    (570, 400),  # location 9
    (912, 400),  # location 10
    (114, 480),  # location 11
    (228, 480),  # location 12
    (342, 560),  # location 13
    (684, 560),  # location 14
    (0, 640),    # location 15
    (798, 640),  # location 16
]
DEMANDS = [0, 1, 1, 2, 4, 2, 4, 8, 8, 1, 2, 1, 2, 4, 4, 8, 8]

m = Model()

m.add_vehicle_type(capacity=15, num_available=4, fixed_cost=10)
m.add_vehicle_type(capacity=20, num_available=6, fixed_cost=10)

depot = m.add_depot(x=COORDS[0][0], y=COORDS[0][1])
clients = [
    m.add_client(x=COORDS[idx][0], y=COORDS[idx][1], demand=DEMANDS[idx])
    for idx in range(1, len(COORDS))
]

locations = [depot, *clients]
for frm in locations:
    for to in locations:
        distance = abs(frm.x - to.x) + abs(frm.y - to.y)  # Manhattan
        m.add_edge(frm, to, distance=distance)

from pyvrp.stop import MaxRuntime

res = m.solve(stop=MaxRuntime(10))  
print(res)
```

#### Describe the solution you'd like
This instance should be solved after ten seconds.

#### Describe alternatives you have considered
None.

#### Additional context
Some observations:
- It hangs in the application of node ops. (Could also hang in route ops, but it hangs when I add no route ops.)
- I suspect it has something to do with two opt. Exchange (1, 0) together with TwoOpt hangs. Only TwoOpt does not hang, probably due to smaller search space.
- Might be related to #369?

**Comment by leonlan** [comment] 2023-09-04 11:14
Might have to do something with TwoOpt & empty route moves.

**Comment by N-Wouda** [comment] 2023-09-04 11:22
Can reproduce with just (1, 0)-exchange and 2-OPT, but I don't have time today to look into this.

**Comment by N-Wouda** [comment] 2023-09-04 11:25
2-OPT does not evaluate fixed cost changes due to routes being used/emptied, because I assumed 2-OPT would not empty routes. But that could be wrong, and causing this.

**Comment by N-Wouda** [comment] 2023-09-04 11:46
Yeah that's probably it. The fix is fairly trivial. Can we add two tests for this? I'm thinking:
- One simple, constructed example in `test_TwoOpt.py` with e.g. two routes, one empty and one non-empty. The non-empty route has load violations taht would be fixed by moveing to the non-empty route (different vehicle type), but that's not worthwhile because of fixed cost differences. Then we check the delta cost is evaluated correctly, taking the fixed cost diff into account.
- A high-level test in `test_Model.py` that reproduces the issue using e.g. the `small_cvrp` instance and the two vehicle types from above. I'm pretty sure that'll also hang on current mian.

**Comment by leonlan** [comment] 2023-09-04 11:50
Sure thing!

**Closed** 2023-09-04 14:03 UTC
Labels: bug
